# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EnjoyLive' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire', '~> 4.3'
    pod 'MJExtension'
    pod 'YYWebImage'


  target 'EnjoyLiveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EnjoyLiveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
